[myosotis]
; hardcoded steam token
token=TOTALLYLEGITTOKEN
; redirect target (must include scheme + trailing slash)
server=http://127.0.0.1:3000/
; redirect target for /serverinfos_* requests
serverinfos_url=http://127.0.0.1:3000/serverinfos.json
; 0 = only error logs, 1 = error & info, 2 = error & info & debug
log_level=1
; 0 = off, 1 = types, 2 = types + il2cpp (shitty)
dump_level=1
