#!/usr/bin/env python3
"""Regenerate the embedded il2cpp name map and canonical name list.

Run after a Limbus update (or whenever you want the embedded fallback in sync):
    python cpp/tools/regen_map.py --game-dir "C:/Program Files (x86)/Steam/steamapps/common/Limbus Company"

This re-runs analyze_mapping.py against UnityPlayer.dll and writes:
    cpp/generated/il2cpp_map.generated.h    (canonical -> obfuscated table)
    cpp/generated/il2cpp_names.generated.h  (canonical name array)

The runtime byte-pattern scan in the DLL is the primary resolver; the embedded
table is only used if the runtime scan fails (e.g. UnityPlayer layout shifts in
a way the scanner doesn't handle). Keeping it in sync is cheap insurance.
"""
import argparse, os, sys

# analyze_mapping.py lives alongside this script in tools/.
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import analyze_mapping as am  # noqa: E402
import pefile  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--game-dir", required=True)
    args = ap.parse_args()

    unity = os.path.join(args.game_dir, "UnityPlayer.dll")
    up = pefile.PE(unity, fast_load=True)
    mapping = am.analyze_mapping(up)
    print(f"resolved {len(mapping)} names")

    os.makedirs(os.path.join(HERE, "..", "generated"), exist_ok=True)
    map_path = os.path.join(HERE, "..", "generated", "il2cpp_map.generated.h")
    with open(map_path, "w") as f:
        f.write("// Auto-generated by regen_map.py from analyze_mapping.py\n")
        f.write("// canonical il2cpp name -> obfuscated GameAssembly.dll export name\n")
        f.write("#pragma once\n")
        f.write("static const struct { const char* canonical; const char* obfuscated; } IL2CPP_MAP[] = {\n")
        for k, v in mapping.items():
            f.write(f'    {{"{k}", "{v}"}},\n')
        f.write("};\n")
        f.write(f"static const size_t IL2CPP_MAP_COUNT = {len(mapping)};\n")
    print(f"wrote {map_path}")

    names_path = os.path.join(HERE, "..", "generated", "il2cpp_names.generated.h")
    with open(names_path, "w") as f:
        f.write("// Auto-generated by regen_map.py from analyze_mapping.py::il2cpp_names\n")
        f.write("#pragma once\n")
        f.write("static const char* const IL2CPP_NAMES[] = {\n")
        for n in am.il2cpp_names:
            f.write(f'    "{n}",\n')
        f.write("};\n")
        f.write(f"static const size_t IL2CPP_NAMES_COUNT = {len(am.il2cpp_names)};\n")
    print(f"wrote {names_path}")


if __name__ == "__main__":
    main()
